stages:
  - RunMake
  - RunTest
  - RunPackage

RunMake:
  stage: RunMake
  script:
    - make
    - mkdir -p artifacts
    - cp simple_num artifacts/
  artifacts:
    paths:
      - artifacts/

RunTest:
  stage: RunTest
  script:
    - chmod +x artifacts/simple_num
    - ./artifacts/simple_num 2 | grep "1"
    - ./artifacts/simple_num 4 | grep "0"
    - ./artifacts/simple_num 7 | grep "1"

RunPackage:
  stage: RunPackage
  script:
    - mkdir -p artifacts/deb
    - mkdir -p artifacts/deb/usr/local/bin
    - cp artifacts/simple_num artifacts/deb/usr/local/bin/
    - dpkg-deb --build artifacts/deb simple_num.deb
  artifacts:
    paths:
      - simple_num.deb
