name: CI Pipeline
on:
  push:
    branches:
      - lab3
jobs:
  RunMake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential dpkg

      - name: Run Make
        run: |
          cd src
          make || { echo "Make failed"; exit 1; }
          ls -l
          mkdir -p ../artifacts
          cp ../usr/bin/simple_num ../artifacts/ || { echo "Failed to copy simple_num to artifacts"; exit 1; }

      - name: Upload Artifact (Binary)
        uses: actions/upload-artifact@v4
        with:
          name: simple_num-binary
          path: artifacts/
  RunTest:
    needs: RunMake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: simple_num-binary
          path: artifacts/
      - name: Run Tests
        run: |
          chmod +x artifacts/simple_num
          echo "Running simple_num with argument 2"
          ./artifacts/simple_num 2
          echo "Running simple_num with argument 4"
          ./artifacts/simple_num 4
          echo "Running simple_num with argument 7"
          ./artifacts/simple_num 7
  RunPackage:
    needs: RunTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: simple_num-binary
          path: artifacts/

      - name: Create Debian Package
        run: |
          mkdir -p artifacts/deb/usr/local/bin
          mkdir -p artifacts/deb/DEBIAN
          cp DEBIAN/control artifacts/deb/DEBIAN/
          cp artifacts/simple_num artifacts/deb/usr/local/bin/
          dpkg-deb --build artifacts/deb simple_num.deb
      - name: Upload Debian Package
        uses: actions/upload-artifact@v4
        with:
          name: simple_num-deb
          path: simple_num.deb
  RunDeploy:
    needs: RunPackage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Debian Package
        uses: actions/download-artifact@v4
        with:
          name: simple_num-deb
          path: ./  # загрузить в текущую директорию

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .  # Используем текущую директорию как контекст
          file: ./Dockerfile
          push: true
          tags: birthtree/simple_num:latest

      - name: Run Container
        run: |
          docker run --rm birthtree/simple_num 10

